function getSocialMedias() {
  return [
    {
      name: 'instagram',
      displayName: 'Instagram',
      url: 'https://www.instagram.com/',
      img: 'icons/instagram.png',
      enabled: true,
    },
    {
      name: 'whatsapp',
      displayName: 'Whatsapp',
      url: 'https://web.whatsapp.com/',
      img: 'icons/whatsapp.png',
      enabled: true,
    },
    {
      name: 'gmail',
      displayName: 'Gmail',
      url: 'https://mail.google.com/',
      img: 'icons/gmail.png',
      enabled: true,
    },
    {
      name: 'youTube',
      displayName: 'YouTube',
      url: 'https://www.youtube.com/',
      img: 'icons/youtube.png',
      enabled: true,
    },
    {
      name: 'facebook',
      displayName: 'Facebook',
      url: 'https://www.facebook.com/',
      img: 'icons/facebook.png',
      enabled: true,
    },
    {
      name: 'messenger',
      displayName: 'Messenger',
      url: 'https://www.messenger.com/',
      img: 'icons/messenger.png',
      enabled: true,
    },
    {
      name: 'linkedIn',
      displayName: 'LinkedIn',
      url: 'https://www.linkedin.com/',
      img: 'icons/linkedin.png',
      enabled: true,
    },
    {
      name: 'telegram',
      displayName: 'Telegram',
      url: 'https://web.telegram.org/#/im/',
      img: 'icons/telegram.png',
      enabled: true,
    },
    {
      name: 'spotify',
      displayName: 'Spotify',
      url: 'https://open.spotify.com/',
      img: 'icons/spotify.png',
      enabled: true,
    },
    {
      name: 'discord',
      displayName: 'Discord',
      url: 'https://discord.com/app/',
      img: 'icons/discord.png',
      enabled: true,
    },
    {
      name: 'github',
      displayName: 'GitHub',
      url: 'https://github.com/',
      img: 'icons/github.png',
      enabled: true,
    },
    {
      name: 'outlook',
      displayName: 'OutLook',
      url: 'https://outlook.live.com/mail/',
      img: 'icons/outlook.png',
      enabled: true,
    },
    {
      name: 'mega',
      displayName: 'Mega',
      url: 'https://mega.nz/',
      img: 'icons/mega.png',
      enabled: true,
    },
    {
      name: 'drive',
      displayName: 'Drive',
      url: 'https://drive.google.com/drive/',
      img: 'icons/drive.png',
      enabled: true,
    },
  ];
};